baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Krishnamohan | Web Dev | Digital Marketing | Content Writing"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "PNM Krishna, Zanskar Hostel, IIT Delhi, Delhi, India"
author = "Krishnamohan"
copyright = "Site is built with Love. Copy rights reserved"
description = ""
email = "krishnamohan.mme@gmail.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/logo.png"
phone = "+91 7013370937"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/krishnamohanpaluri"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.instagram.com/krishpaluri/"
icon = "ti-instagram"
[[params.social]]
URL = "https://twitter.com/Krishnamohan4u"
icon = "ti-twitter-alt"
